/**
 * 系统常量定义
 */

// 用户角色
const USER_ROLE = {
  ADMIN: 0,
  AGENT: 1,
};

// 用户状态
const USER_STATUS = {
  DISABLED: 0,
  ENABLED: 1,
};

// 线索状态
const LEAD_STATUS = {
  PENDING: 0,
  FOLLOWING: 1,
  VIEWED: 2,
  QUOTED: 3,
  DEAL: 4,
  FAILED: 5,
};

// 线索状态流转规则
const LEAD_STATUS_FLOW = {
  [LEAD_STATUS.PENDING]: [LEAD_STATUS.FOLLOWING],
  [LEAD_STATUS.FOLLOWING]: [LEAD_STATUS.VIEWED, LEAD_STATUS.FAILED],
  [LEAD_STATUS.VIEWED]: [LEAD_STATUS.QUOTED, LEAD_STATUS.FAILED],
  [LEAD_STATUS.QUOTED]: [LEAD_STATUS.DEAL, LEAD_STATUS.FAILED],
  [LEAD_STATUS.DEAL]: [],
  [LEAD_STATUS.FAILED]: [],
};

// 结算状态
const SETTLEMENT_STATUS = {
  PENDING: 0,
  SETTLED: 1,
};

// 操作类型
const OPERATION_TYPE = {
  LOGIN: 0,
  CREATE: 1,
  UPDATE: 2,
  DELETE: 3,
  OTHER: 4,
};

// 操作目标
const OPERATION_TARGET = {
  LEAD: 0,
  SETTLEMENT: 1,
  USER: 2,
  OTHER: 3,
};

// 错误码
const ERROR_CODES = {
  SUCCESS: 0,
  PARAM_ERROR: 1,
  AUTH_FAILED: 2,
  NOT_FOUND: 3,
  SYSTEM_ERROR: 4,
  INVALID_STATUS_FLOW: 10,
  MISSING_REQUIRED_PARAM: 11,
  FINAL_STATUS_CANNOT_MODIFY: 12,
  LEAD_NOT_DEAL: 13,
  AGENT_SHARE_EXCEED_PROFIT: 14,
  SETTLEMENT_EXISTS: 15,
  SETTLED_CANNOT_MODIFY_AMOUNT: 16,
  NOTIFY_TOO_FREQUENT: 17,
  PHONE_BOUND_TO_OTHER: 18,
  USERID_EXISTS: 19,
  PHONE_EXISTS: 20,
  PHONE_FORMAT_ERROR: 21,
  NEED_BIND_PHONE: 22,
  TOO_MANY_REQUESTS: 429,
};

// 错误码对应消息
const ERROR_MESSAGES = {
  [ERROR_CODES.SUCCESS]: 'success',
  [ERROR_CODES.PARAM_ERROR]: '参数错误',
  [ERROR_CODES.AUTH_FAILED]: '鉴权失败',
  [ERROR_CODES.NOT_FOUND]: '数据不存在',
  [ERROR_CODES.SYSTEM_ERROR]: '系统错误',
  [ERROR_CODES.INVALID_STATUS_FLOW]: '状态流转非法',
  [ERROR_CODES.MISSING_REQUIRED_PARAM]: '缺少必填参数',
  [ERROR_CODES.FINAL_STATUS_CANNOT_MODIFY]: '终态不可修改',
  [ERROR_CODES.LEAD_NOT_DEAL]: '线索未成交，无法创建结算',
  [ERROR_CODES.AGENT_SHARE_EXCEED_PROFIT]: '分成金额不能大于利润金额',
  [ERROR_CODES.SETTLEMENT_EXISTS]: '该线索已存在结算记录',
  [ERROR_CODES.SETTLED_CANNOT_MODIFY_AMOUNT]: '已结算记录不可修改金额',
  [ERROR_CODES.NOTIFY_TOO_FREQUENT]: '5分钟内已推送过提醒',
  [ERROR_CODES.PHONE_BOUND_TO_OTHER]: '手机号已被其他微信账号绑定',
  [ERROR_CODES.USERID_EXISTS]: 'userid已存在',
  [ERROR_CODES.PHONE_EXISTS]: '手机号已存在',
  [ERROR_CODES.PHONE_FORMAT_ERROR]: '手机号格式错误',
  [ERROR_CODES.NEED_BIND_PHONE]: '请先绑定手机号',
  [ERROR_CODES.TOO_MANY_REQUESTS]: '请求过于频繁，请稍后再试',
};

module.exports = {
  USER_ROLE,
  USER_STATUS,
  LEAD_STATUS,
  LEAD_STATUS_FLOW,
  SETTLEMENT_STATUS,
  OPERATION_TYPE,
  OPERATION_TARGET,
  ERROR_CODES,
  ERROR_MESSAGES,
};
